# Generated by Django 5.1.7 on 2025-03-21 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('opc_code', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('order_number', models.CharField(max_length=255)),
                ('customer_number', models.CharField(max_length=255)),
                ('purchase_order_number', models.CharField(max_length=255)),
                ('ship_date', models.DateField()),
                ('cancel_date', models.DateField(blank=True, null=True)),
                ('tray_no', models.CharField(blank=True, max_length=255, null=True)),
                ('rush', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_ordered', models.IntegerField()),
                ('quantity_shipped', models.IntegerField()),
                ('quantity_backordered', models.IntegerField()),
                ('order_date', models.DateField()),
                ('ship_date', models.DateField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.item')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.manufacturer')),
            ],
        ),
    ]
